# Generated by Django 4.1.7 on 2023-02-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewards_name', models.CharField(max_length=50)),
                ('rewards_description', models.CharField(max_length=300)),
                ('rewards_cost', models.IntegerField(default=0)),
            ],
        ),
    ]
