# Generated by Django 4.1.7 on 2023-02-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('avatar_url', models.URLField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=20)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=15)),
                ('phone', models.CharField(max_length=20)),
                ('habits', models.JSONField()),
                ('achievements', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewards_name', models.CharField(max_length=50)),
                ('rewards_description', models.CharField(max_length=300)),
                ('rewards_cost', models.IntegerField(default=0)),
                ('person', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='People.person')),
            ],
        ),
    ]
