# Generated by Django 4.1.7 on 2023-02-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('avatar_url', models.URLField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=20)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=15)),
                ('phone', models.CharField(max_length=20)),
                ('habits', models.JSONField()),
                ('achievements', models.JSONField()),
            ],
        ),
    ]
