# Generated by Django 4.1.7 on 2023-02-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewards',
            old_name='person',
            new_name='user_id',
        ),
    ]
