# Generated by Django 4.1.7 on 2023-02-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0002_rename_person_rewards_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='habits',
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_name', models.CharField(max_length=100)),
                ('habit_category', models.CharField(max_length=100)),
                ('habit_type', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='People.person')),
            ],
        ),
    ]
