# Generated by Django 4.1.7 on 2023-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0003_remove_person_habits_habits'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='habit_streak',
            field=models.IntegerField(default=0),
        ),
    ]
