# Generated by Django 4.1.7 on 2023-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=100)),
                ('achievement_img_url', models.URLField(max_length=300)),
                ('achievement_description', models.CharField(max_length=300)),
                ('achievement_unlock', models.BooleanField(default=False)),
                ('achievement_reward', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
