# Generated by Django 4.1.7 on 2023-02-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Achievements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='achievements_reward',
            new_name='achievement_reward',
        ),
    ]
