# Generated by Django 4.1.7 on 2023-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achievements', '0002_rename_achievements_reward_achievements_achievement_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='achievement_unlock',
            field=models.BooleanField(default=False),
        ),
    ]
